name: Feature Validation

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m venv env
          . env/bin/activate && pip install --upgrade pip
          . env/bin/activate && pip install -r requirements.txt
      - name: Run tests
        run: |
          . env/bin/activate && make test
